### ISSUE TITLE
Empty notes

### ISSUE THREAD

**Issue by py-b** [iandees/planet-notes-dump#12]
Hello,

Since few weeks, some empty notes (without a single comment) appear in the osn file :

`<note id="541817" lat="0.0000000" lon="0.0000000" created_at="2016-04-07T12:40:25Z"/>`
http://www.openstreetmap.org/note/541817

Do you know how they were created ? Do you plan to remove them from the output file ?

Regards,

**Comment by iandees** [comment]
These appear to be a bug/feature of OSM.org and are actually getting created. Not sure how, but I've noticed them in other places, too. I don't think we should remove them from the output of planet-notes-dump.

**Comment by py-b** [comment]
Thanks for your quick response!

Have you reported the bug to the persons in charge of osm notes, if you know them? I would like to do so, but don't know where to post a message.

By the way, thanks for your work! Very useful to me for the analyse of notes in France.

**Comment by iandees** [comment]
You might want to ask TomH or @Firefishy on IRC (in the #osm-dev channel) first, but the bug should probably go to https://github.com/openstreetmap/openstreetmap-website.

**Comment by py-b** [comment]
Done!
https://github.com/openstreetmap/openstreetmap-website/issues/1203

**Comment by DeeHants** [comment]
FYI, all bar one of the notes has been closed (after fixing a bug in JOSM).
The remaining one is left for testing.
