### ISSUE TITLE
Rename date_created and date_closed

### ISSUE THREAD

**Issue by Zverik** [iandees/planet-notes-dump#6]
Just a suggestion, of course, but it would make files more consistent. Look at a changeset header:

``` xml
<changeset id="23800009" user="dimi_d" uid="471087" created_at="2014-07-03T12:54:05Z" closed_at="2014-07-03T12:54:06Z" open="false" min_lat="60.0564017" min_lon="30.3104757" max_lat="60.0575618" max_lon="30.3142499">
  <tag k="source" v="knowledge"/>
  <tag k="created_by" v="JOSM/1.5 (7182 ru)"/>
</changeset>
```

I propose to rename `date_created` and `date_closed` attributes of `<note>` to `created_at` and `closed_at` respectively, like for changesets.

**Comment by joto** [comment]
The comments in the notes have `action="opened"` and `action="closed"`, so to be consistent with them it would be `date_opened` and `date_closed`. Or maybe the actions have to be renamed?

On the other hand, do we need the attributes on the `note` tag if we always have those comments anyway? Hm, I see there is a `reopened` action which would influence this. It is not immediately clear how those `date_created` and `date_closed` relate to the dates in the comments.
