### ISSUE TITLE
Get rid of <comments> tag

### ISSUE THREAD

**Issue by Zverik** [iandees/planet-notes-dump#7]
I propose making `<comment>` tag a child of `<note>` itself, without `<comments>` wrapper. It is in line with other osm objects xml representations: remember `<tag>` and `<member>` elements, for example.

**Comment by joto** [comment]
:+1:

**Comment by harry-wood** [comment]
So should the notes API change? (e.g. http://api.openstreetmap.org/api/0.6/notes/100 )  I would've expected the two to be kept consistent either way:

**Comment by Zverik** [comment]
Notes API is awful. Why ID in a separate tag? Why URLs and HTML? Why tags in comments, and not attributes? I understand it was to quicken front-end development, but it is no public API.

**Comment by Zverik** [comment]
I propose to keep old one under `/notes` and make a new, proper API under `/note` (singular, re: `/node`, `/changeset`).

**Comment by iandees** [comment]
Hi folks, let's move the discussion to the correct repo please.
