### ISSUE TITLE
Why .osm?

### ISSUE THREAD

**Issue by joto** [iandees/planet-notes-dump#8]
Can we come up with a standard filename suffix right away. `.xml` isn't so great.

**Comment by Firefishy** [comment]
Filename suffix was my choice, any suggestion? Maybe? `.osm-notes`

**Comment by joto** [comment]
We have `.osm` and `.osc` and some use `.osh` for history dumps. How about `.osn`? Hm, maybe to similar to `.osm`. `ont` ? Maybe @Firefishy is right and we don't have to keep this three-character-suffix thing going but have an understandable suffix.

**Comment by Firefishy** [comment]
I'll use `.osn`. 

`.ont` conflicts with a widely used extension.

**Comment by iandees** [comment]
Sounds like @Firefishy will fix this when he's running it.
